### ISSUE TITLE
Option Add url, method, mode, threads and dates to the name report does not work on windows 10

### ISSUE THREAD

**Issue by TacEtarip** [jrichardsz-software-architect-tools/stressify#13]
![errorimage2](https://user-images.githubusercontent.com/55962686/143469309-83b02ec0-9935-4b8b-8e6a-9c1767f10ea0.jpg)

When that option is checked the report will run but the app throws an error and won't create the report files. The error is (click the image to view):

![errorimage](https://user-images.githubusercontent.com/55962686/143469644-59a579a8-588b-4ef8-a4d0-7306c42cdc52.jpg)

Full error log with 1 VU:

```
2021-11-25 10:40:36,249 AWT-EventQueue-0 ERROR Null object returned for File in Appenders.
2021-11-25 10:40:36,252 AWT-EventQueue-0 ERROR Unable to locate appender "MyFile" for logger config "root"
10:40:36.254 [AWT-EventQueue-0] INFO  org.jrichardsz.tools.stressify.mode.SimpleGraphicStressor - Stress starting with uuid:20b651ab-3f83-4746-b465-8d3956ed8416
10:40:36.254 [AWT-EventQueue-0] INFO  org.jrichardsz.tools.stressify.mode.SimpleGraphicStressor - Data csv file is not configured. Stresss will not use variables. Go to data section and configure it if you want to use variables!
10:40:36.255 [AWT-EventQueue-0] INFO  org.jrichardsz.tools.stressify.mode.SimpleGraphicStressor - assert script is not configured.
10:40:36.255 [AWT-EventQueue-0] INFO  org.jrichardsz.tools.stressify.mode.SimpleGraphicStressor - Parameters:
10:40:36.255 [AWT-EventQueue-0] INFO  org.jrichardsz.tools.stressify.mode.SimpleGraphicStressor - data file:
10:40:36.255 [AWT-EventQueue-0] INFO  org.jrichardsz.tools.stressify.mode.SimpleGraphicStressor - report columns:id,startDate,endDate,responseStatus,asserts,totalExecutionMillisTime,log
10:40:36.256 [AWT-EventQueue-0] INFO  org.jrichardsz.tools.stressify.mode.SimpleGraphicStressor - mode:sequential
10:40:36.256 [AWT-EventQueue-0] INFO  org.jrichardsz.tools.stressify.mode.SimpleGraphicStressor - virtual users:1
10:40:46.271 [AWT-EventQueue-0] INFO  org.jrichardsz.tools.stressify.rest.ContinuosRestClient - http invocation was completed. Id: 2cff3386-aa0c-4846-9408-338402d4518e
10:40:46.272 [AWT-EventQueue-0] INFO  org.jrichardsz.tools.stressify.rest.ContinuosRestClient - 2cff3386-aa0c-4846-9408-338402d4518e Request values : Url:http://localhost:1000/event?event-identifier=process_stress_event&access-key=asecurekey Headers:{Content-Type=application/json} Method:POST Body:
10:40:46.273 [AWT-EventQueue-0] INFO  org.jrichardsz.tools.stressify.rest.ContinuosRestClient - 2cff3386-aa0c-4846-9408-338402d4518e Response values : {totalExecutionMillisTime=10015, Keep-Alive=timeout=5, responseBody={"code":500000,"message":"Server Internal Error"}, Access-Control-Allow-Origin=*, X-Content-Type-Options=nosniff, Connection=keep-alive, endMillisDate=1637854846271, X-Download-Options=noopen, startMillisDate=1637854836256, X-Permitted-Cross-Domain-Policies=none, responseStatus=500, Date=Thu, 25 Nov 2021 15:40:46 GMT, Referrer-Policy=no-referrer, X-Frame-Options=SAMEORIGIN, default=HTTP/1.1 500 Internal Server Error, Strict-Transport-Security=max-age=15552000; includeSubDomains, ETag=W/"31-U1OaLXtEryw0pAOuA0B2ZrNFIs4", Content-Security-Policy=default-src 'self';base-uri 'self';block-all-mixed-content;font-src 'self' https: data:;frame-ancestors 'self';img-src 'self' data:;object-src 'none';script-src 'self';script-src-attr 'none';style-src 'self' https: 'unsafe-inline';upgrade-insecure-requests, Vary=Accept-Encoding, X-DNS-Prefetch-Control=off, Content-Length=49, X-XSS-Protection=0, Content-Type=application/json; charset=utf-8, Expect-CT=max-age=0}
java.io.FileNotFoundException: D:\usil\stress\miercoles-_event?event-identifier=process_stress_event&access-key=asecurekey-POST-sequential-1-date-2021-11-25-10-40-36-uuid-20b651ab-3f83-4746-b465-8d3956ed8416-report.csv (El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileWriter.<init>(Unknown Source)
        at org.jrichardsz.tools.stressify.steps.ReportStep.execute(ReportStep.java:22)
        at org.jrichardsz.tools.stressify.mode.SimpleGraphicStressor.perform(SimpleGraphicStressor.java:126)
        at org.jrichardsz.tools.stressify.controllers.project.stress.ProjectStressorController.stress(ProjectStressorController.java:149)
        at org.jrichardsz.tools.stressify.controllers.project.stress.ProjectStressorController.actionPerformed(ProjectStressorController.java:88)
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
        at java.awt.Component.processMouseEvent(Unknown Source)
        at javax.swing.JComponent.processMouseEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by jrichardsz** [comment]
fixed with https://github.com/jrichardsz-software-architect-tools/stressify/pull/14
